In [24]:
import pandas as pd

In [23]:
import pandas as pd
df =pd.read_excel("maniproject2.xlsx")
df.head(30)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
5,2020-01-01,00:05:00,Canada,F,44,73,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,2020-01-01,00:06:00,USA,F,80,70,White,Signal Violation,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
7,2020-01-01,00:07:00,India,M,72,50,Asian,Drunk Driving,Other,False,NaN,Arrest,True,30+ Min,True,DL75KZ7835
8,2020-01-01,00:08:00,USA,F,80,30,Hispanic,Other,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
9,2020-01-01,00:09:00,USA,M,43,21,Asian,Signal Violation,Signal,True,NaN,Warning,True,16-30 Min,False,KA79RD2271
10,2020-01-01,00:10:00,India,F,66,76,Black,Speeding,Signal,False,NaN,Ticket,False,30+ Min,True,UP67CQ9426
11,2020-01-01,00:11:00,Canada,F,58,53,Hispanic,Signal Violation,Signal,False,Vehicle Search,Arrest,True,30+ Min,True,KA61JB1004
12,2020-01-01,00:12:00,India,M,51,46,Asian,Drunk Driving,Signal,False,Vehicle Search,Ticket,False,16-30 Min,True,WB70IV9884
13,2020-01-01,00:13:00,USA,M,55,58,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,WB56XQ8946
14,2020-01-01,00:14:00,India,M,44,25,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,GJ67CO6825
15,2020-01-01,00:15:00,USA,F,65,51,Hispanic,Other,DUI,True,Frisk,Ticket,False,16-30 Min,True,WB75TF1052
16,2020-01-01,00:16:00,India,M,75,21,Asian,Seatbelt,Speeding,True,Vehicle Search,Arrest,False,16-30 Min,False,UP82DB7554
17,2020-01-01,00:17:00,Canada,F,44,55,White,Signal Violation,Other,True,Vehicle Search,Warning,True,0-15 Min,True,MH15GS2782
18,2020-01-01,00:18:00,USA,M,46,71,White,Speeding,Speeding,True,Frisk,Warning,True,16-30 Min,True,MH80WR1351
19,2020-01-01,00:19:00,Canada,F,42,41,Hispanic,Signal Violation,Signal,False,NaN,Arrest,False,30+ Min,False,KA12GK6861
20,2020-01-01,00:20:00,USA,F,76,47,Hispanic,Signal Violation,Signal,False,NaN,Warning,False,0-15 Min,True,KA78HN8680
21,2020-01-01,00:21:00,Canada,F,56,25,Black,Other,DUI,True,Frisk,Arrest,False,0-15 Min,False,WB35BJ2947
22,2020-01-01,00:22:00,USA,F,25,59,Asian,Other,Speeding,False,NaN,Ticket,True,0-15 Min,True,GJ46IJ2247
23,2020-01-01,00:23:00,Canada,F,47,60,Black,Signal Violation,Signal,True,Frisk,Arrest,True,0-15 Min,False,GJ24GN5905
24,2020-01-01,00:24:00,India,M,33,76,Hispanic,Signal Violation,Speeding,False,NaN,Warning,False,16-30 Min,False,MH83XS7688
25,2020-01-01,00:25:00,USA,F,18,58,White,Other,Speeding,False,Frisk,Ticket,False,16-30 Min,True,KA95EW9912
26,2020-01-01,00:26:00,Canada,F,20,56,Asian,Drunk Driving,Other,False,NaN,Ticket,True,0-15 Min,False,DL36PY9336
27,2020-01-01,00:27:00,India,F,63,61,Other,Drunk Driving,Signal,True,Vehicle Search,Warning,False,0-15 Min,False,MH17TG9873
28,2020-01-01,00:28:00,USA,F,71,69,Hispanic,Seatbelt,Seatbelt,False,Vehicle Search,Ticket,True,0-15 Min,False,GJ67TR1208
29,2020-01-01,00:29:00,USA,M,51,39,Hispanic,Other,Seatbelt,True,Vehicle Search,Arrest,False,30+ Min,True,RJ65DM5842

In [8]:
df.shape

(65538, 16)

In [33]:
df.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [27]:
df['search_type'] = df['search_type'].ffill()

In [29]:
df.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [31]:
df.to_excel("cleaned_data.xlsx", index=False)

In [35]:
import os
os.getcwd()

'D:\\guvi data science'

In [43]:
folder_path = "D:/Users/YourUsername/Documents"
os.makedirs(folder_path, exist_ok=True)  # This will create the folder if it doesn't exist

file_path = os.path.join(folder_path, "cleaned_data.xlsx")
df.to_excel(file_path, index=False)

In [17]:
df.dtypes

stop_date             datetime64[ns]
stop_time                     object
country_name                  object
driver_gender                 object
driver_age_raw                 int64
driver_age                     int64
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
drugs_related_stop              bool
vehicle_number                object
dtype: object

In [12]:
import mysql.connector

mydb = mysql.connector.connect(
    host = "localhost",
    user = "mani",
    password="1234"
)

mycursor = mydb.cursor(buffered=True)

In [99]:
mycursor.execute("SHOW DATABASES")

for x in mycursor:
    print(x)

('information_schema',)
('mani db',)
('mdte19',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('test',)

In [101]:
mycursor.execute("CREATE DATABASE police_post")

In [18]:
mycursor.execute("use police_post")

In [107]:
mycursor.execute("""
CREATE TABLE traffic_stops (
    stop_date DATE,
    stop_time TIME,
    country_name VARCHAR(80),
    driver_gender VARCHAR(1),
    driver_age_raw INT,
    driver_age INT,
    driver_race VARCHAR(50),
    violation_raw VARCHAR(100),
    violation VARCHAR(100),
    search_conducted BOOLEAN,
    search_type VARCHAR(100),
    stop_outcome VARCHAR(100),
    is_arrested FLOAT,
    stop_duration VARCHAR(50),
    drugs_related_stop BOOLEAN,
    vechicle_number VARCHAR(50)
)
""")

In [146]:
# batch_size = 100  # You can adjust this based on your machine

# for start in range(0, len(values), batch_size):
#     end = start + batch_size
#     batch = values[start:end]
#     mycursor.executemany(sql, batch)
#     mydb.commit()

In [148]:
# sql = """
# INSERT INTO traffic_stops (
#     stop_date, stop_time, country_name, driver_gender, driver_age_raw, driver_age, driver_race,
#     violation_raw, violation, search_conducted, search_type,
#     stop_outcome, is_arrested, stop_duration, drugs_related_stop, vechicle_number
# ) 
# VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
# """

# # Create list of tuples from DataFrame
# values = [
#     (
#         row.stop_date, row.stop_time, row.country_name, row.driver_gender,
#         row.driver_age_raw, row.driver_age, row.driver_race,
#         row.violation_raw, row.violation, row.search_conducted, row.search_type,
#         row.stop_outcome, row.is_arrested, row.stop_duration,
#         row.drugs_related_stop, row.vehicle_number
#     )
#     for index, row in df.iterrows()
# ]

# # Execute many
# mycursor.executemany(sql, values)
# mydb.commit()

In [150]:
df.shape

(65538, 16)

In [8]:
!pip install tabulate

from tabulate import tabulate

Requirement already satisfied: tabulate in c:\users\user\anaconda3\lib\site-packages (0.9.0)

In [154]:
# 1 Total Number of Police Stops
mycursor.execute("SELECT COUNT(*) AS total_police_stops FROM traffic_stops;")
out=mycursor.fetchall()
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

+----------------------+
|   total_police_stops |
|----------------------|
|               327690 |
+----------------------+

In [156]:
# 2 Count of Stops by Violation Type

query = """
SELECT 
    violation,
    COUNT(*) AS stop_count
FROM 
    traffic_stops
GROUP BY 
    violation
ORDER BY 
    stop_count DESC;
"""

mycursor.execute(query)
results = mycursor.fetchall()

# Print results
for row in results:
    print(f"Violation: {row[0]}, Stops: {row[1]}")

Violation: Other, Stops: 65970
Violation: Speeding, Stops: 65750
Violation: Signal, Stops: 65560
Violation: DUI, Stops: 65375
Violation: Seatbelt, Stops: 65035

In [160]:
# 3 Number of Arrests vs. Warnings
query = """
SELECT 
    stop_outcome,
    COUNT(*) AS total
FROM 
    traffic_stops
WHERE 
    stop_outcome IN ('Arrest', 'Warning')
GROUP BY 
    stop_outcome
ORDER BY 
    total DESC;
"""

mycursor.execute(query)
results = mycursor.fetchall()

# Print results

for row in results:
    print(f"Stop Outcome: {row[0]}, Total: {row[1]}")

Stop Outcome: Warning, Total: 109830
Stop Outcome: Arrest, Total: 108670

In [162]:
# 4 Average Age of Drivers Stopped
query = """
SELECT 
    AVG(driver_age) AS average_driver_age
FROM 
    traffic_stops
WHERE 
    driver_age IS NOT NULL;
"""

mycursor.execute(query)
result = mycursor.fetchone()

print(f"Average Driver Age: {result[0]:.2f}")

Average Driver Age: 49.11

In [164]:
# 5 Top 5 Most Frequent Search Types

query = """
SELECT 
    search_type,
    COUNT(*) AS total_searches
FROM 
    traffic_stops
WHERE 
    search_type IS NOT NULL AND search_type != ''
GROUP BY 
    search_type
ORDER BY 
    total_searches DESC
LIMIT 5;
"""

mycursor.execute(query)
results = mycursor.fetchall()

# Print the results
for row in results:
    print(f"Search Type: {row[0]}, Total: {row[1]}")

Search Type: Frisk, Total: 164235
Search Type: Vehicle Search, Total: 163455

In [30]:
# 6 Count of Stops by Gender
!pip install prettytable
from prettytable import PrettyTable

query = """
SELECT 
    driver_gender,
    COUNT(*) AS total_stops
FROM 
    traffic_stops
WHERE 
    driver_gender IS NOT NULL
GROUP BY 
    driver_gender;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()
# Create and display the table
table = PrettyTable()
table.field_names = ["Driver Gender", "Total Stops"]

for row in results:
    table.add_row(row)

print(table)

Requirement already satisfied: prettytable in c:\users\user\anaconda3\lib\site-packages (3.16.0)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prettytable) (0.2.5)
+---------------+-------------+
| Driver Gender | Total Stops |
+---------------+-------------+
|       F       |    164405   |
|       M       |    163285   |
+---------------+-------------+

In [168]:
# 7 Most Common Violation for Arrests

query = """
SELECT 
    violation,
    COUNT(*) AS violation_count
FROM 
    traffic_stops
WHERE 
    is_arrested = 1
GROUP BY 
    violation
ORDER BY 
    violation_count DESC
LIMIT 1;
"""

# Execute the query
mycursor.execute(query)
result = mycursor.fetchone()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Violation Count"]

# Add the result row to the table
table.add_row(result)

# Print the table
print(table)

+-----------+-----------------+
| Violation | Violation Count |
+-----------+-----------------+
|    DUI    |      33050      |
+-----------+-----------------+

In [32]:
# 8 Average Stop Duration for Each Violation

query = """
SELECT 
    violation,
    AVG(stop_duration) AS average_stop_duration
FROM 
    traffic_stops
WHERE 
    stop_duration IS NOT NULL
GROUP BY 
    violation
ORDER BY 
    average_stop_duration DESC;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Average Stop Duration"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+-----------+-----------------------+
| Violation | Average Stop Duration |
+-----------+-----------------------+
|   Other   |   15.743974533879037  |
|  Seatbelt |   15.334358422387945  |
|  Speeding |   15.286692015209125  |
|    DUI    |   15.234875717017209  |
|   Signal  |    15.2019524100061   |
+-----------+-----------------------+

In [172]:
# 8 Average Stop Duration for Each Violation
query = """
SELECT 
    violation,
    ROUND(AVG(stop_duration), 2) AS average_stop_duration
FROM 
    traffic_stops
WHERE 
    stop_duration IS NOT NULL
GROUP BY 
    violation
ORDER BY 
    average_stop_duration DESC;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Average Stop Duration"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+-----------+-----------------------+
| Violation | Average Stop Duration |
+-----------+-----------------------+
|   Other   |         15.74         |
|  Seatbelt |         15.33         |
|  Speeding |         15.29         |
|    DUI    |         15.23         |
|   Signal  |          15.2         |
+-----------+-----------------------+

In [174]:
# 9 Number of Drug-Related Stops by Year

query = """
SELECT 
    YEAR(stop_date) AS stop_year,
    COUNT(*) AS drug_related_stops
FROM 
    traffic_stops
WHERE 
    drugs_related_stop = 1
GROUP BY 
    stop_year
ORDER BY 
    stop_year ASC;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Year", "Drug-Related Stops"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+------+--------------------+
| Year | Drug-Related Stops |
+------+--------------------+
| 2020 |       163845       |
+------+--------------------+

In [182]:
# 10 Drivers with the Highest Number of Stops
sql = """
SELECT vechicle_number, COUNT(*) AS stop_count
FROM traffic_stops
GROUP BY vechicle_number
ORDER BY stop_count DESC
LIMIT 10;
"""

mycursor.execute(sql)
results = mycursor.fetchall()

# Convert to pandas DataFrame
df_top = pd.DataFrame(results, columns=["Vehicle Number", "Stop Count"])

# Print as a nice table
print(tabulate(df_top, headers='keys', tablefmt='psql', showindex=False))

+------------------+--------------+
| Vehicle Number   |   Stop Count |
|------------------+--------------|
| UP57YR4979       |            5 |
| GJ42NO6708       |            5 |
| DL85TY3790       |            5 |
| WB98CX2862       |            5 |
| RJ44DC2925       |            5 |
| RJ64UW5311       |            5 |
| DL15FG8530       |            5 |
| UP77FA7615       |            5 |
| GJ86TD4778       |            5 |
| RJ85NA1457       |            5 |
+------------------+--------------+

In [186]:
# 11 Number of Stops Conducted at Night (Between 10 PM - 5 AM)
sql = """
SELECT 
    COUNT(*) AS night_stops
FROM 
    traffic_stops
WHERE 
    (stop_time >= '22:00:00' OR stop_time <= '05:00:00');
"""

# Execute the query
mycursor.execute(sql)
result = mycursor.fetchone()

# Display the result
night_stops = result[0]
print(f"Number of Stops Conducted at Night (Between 10 PM - 5 AM): {night_stops}")

Number of Stops Conducted at Night (Between 10 PM - 5 AM): 96230

In [15]:
# 12. Number of Searches Conducted by Violation Type

sql = """
SELECT 
    violation, 
    COUNT(*) AS search_count
FROM 
    traffic_stops
WHERE 
    search_conducted = 1
GROUP BY 
    violation
ORDER BY 
    search_count DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Violation Type", "Search Count"]

# Add rows to the table
for row in results:
    table.add_row(row)
# Print the table
print(table)

+----------------+--------------+
| Violation Type | Search Count |
+----------------+--------------+
|     Other      |    32880     |
|    Speeding    |    32865     |
|    Seatbelt    |    32810     |
|     Signal     |    32545     |
|      DUI       |    32405     |
+----------------+--------------+

In [17]:
# 13. Arrest Rate by Driver Gender

sql = """
SELECT 
    driver_gender,
    COUNT(*) AS total_stops,
    SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests,
    (SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS arrest_rate
FROM 
    traffic_stops
GROUP BY 
    driver_gender
ORDER BY 
    arrest_rate DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Driver Gender", "Total Stops", "Total Arrests", "Arrest Rate (%)"]

# Add rows to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+---------------+-------------+---------------+-----------------+
| Driver Gender | Total Stops | Total Arrests | Arrest Rate (%) |
+---------------+-------------+---------------+-----------------+
|       F       |    164405   |     82765     |     50.3421     |
|       M       |    163285   |     81465     |     49.8913     |
+---------------+-------------+---------------+-----------------+

In [19]:
# 14. Violation Trends Over Time (Monthly Count of Violations)

sql = """
SELECT 
    YEAR(stop_date) AS violation_year,
    MONTH(stop_date) AS violation_month,
    violation,
    COUNT(*) AS violation_count
FROM 
    traffic_stops
GROUP BY 
    violation_year, violation_month, violation
ORDER BY 
    violation_year, violation_month, violation_count DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Year", "Month", "Violation", "Violation Count"]

# Add rows to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+------+-------+-----------+-----------------+
| Year | Month | Violation | Violation Count |
+------+-------+-----------+-----------------+
| 2020 |   1   |   Other   |      44850      |
| 2020 |   1   |  Speeding |      44710      |
| 2020 |   1   |   Signal  |      44615      |
| 2020 |   1   |    DUI    |      44530      |
| 2020 |   1   |  Seatbelt |      44495      |
| 2020 |   2   |   Other   |      21120      |
| 2020 |   2   |  Speeding |      21040      |
| 2020 |   2   |   Signal  |      20945      |
| 2020 |   2   |    DUI    |      20845      |
| 2020 |   2   |  Seatbelt |      20540      |
+------+-------+-----------+-----------------+

In [21]:
# 15.Most Common Stop Outcomes for Drug-Related Stops

sql = """
SELECT 
    stop_outcome,
    COUNT(*) AS outcome_count
FROM 
    traffic_stops
WHERE 
    drugs_related_stop = 1
GROUP BY 
    stop_outcome
ORDER BY 
    outcome_count DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Stop Outcome", "Outcome Count"]

# Add rows to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+--------------+---------------+
| Stop Outcome | Outcome Count |
+--------------+---------------+
|   Warning    |     55290     |
|    Arrest    |     54345     |
|    Ticket    |     54210     |
+--------------+---------------+

Complex questions

In [17]:
# 1.Yearly Breakdown of Stops and Arrests by Country (Using Subquery and Window Functions)

query = """
SELECT 
    country_name,
    stop_year,
    total_stops,
    total_arrests,
    SUM(total_arrests) OVER (PARTITION BY country_name ORDER BY stop_year) AS cumulative_arrests
FROM (
    SELECT 
        country_name,
        YEAR(stop_date) AS stop_year,
        COUNT(*) AS total_stops,
        SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests
    FROM traffic_stops
    GROUP BY country_name, YEAR(stop_date)
) AS yearly_data
ORDER BY country_name, stop_year;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Setup PrettyTable
table = PrettyTable()
table.field_names = ["Country", "Year", "Total Stops", "Total Arrests", "Cumulative Arrests"]

for row in results:
    table.add_row(row)

# Print the formatted table
print(table)

+---------+------+-------------+---------------+--------------------+
| Country | Year | Total Stops | Total Arrests | Cumulative Arrests |
+---------+------+-------------+---------------+--------------------+
|  Canada | 2020 |    109540   |     54995     |       54995        |
|  India  | 2020 |    109990   |     55455     |       55455        |
|   USA   | 2020 |    108160   |     53780     |       53780        |
+---------+------+-------------+---------------+--------------------+

In [ ]:

# query = """
# SELECT 
#     v.age_group,
#     t.driver_race,
#     t.violation,
#     COUNT(*) AS violation_count
# FROM (
#     SELECT 
#         driver_age,
#         CASE 
#             WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
#             WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
#             WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
#             WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
#             WHEN driver_age > 60 THEN '60+'
#             ELSE 'Unknown'
#         END AS age_group
#     FROM traffic_stops
# ) AS v
# JOIN traffic_stops t ON v.driver_age = t.driver_age
# GROUP BY v.age_group, t.driver_race, t.violation
# ORDER BY v.age_group, t.driver_race, violation_count DESC;
# """

# # Execute and fetch
# mycursor.execute(query)
# results = mycursor.fetchall()

# # Display in table
# table = PrettyTable()
# table.field_names = ["Age Group", "Driver Race", "Violation", "Violation Count"]

# for row in results:
#     table.add_row(row)

# print(table)

In [19]:
# 2.Driver Violation Trends Based on Age and Race (Join with Subquery)

query = """
SELECT 
    CASE 
        WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
        WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
        WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
        WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
        WHEN driver_age > 60 THEN '60+'
        ELSE 'Unknown'
    END AS age_group,
    driver_race,
    violation,
    COUNT(*) AS violation_count
FROM traffic_stops
WHERE driver_age IS NOT NULL
GROUP BY age_group, driver_race, violation
ORDER BY age_group, driver_race, violation_count DESC;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Display with PrettyTable
table = PrettyTable()
table.field_names = ["Age Group", "Driver Race", "Violation", "Violation Count"]

for row in results:
    table.add_row(row)

print(table)

+-----------+-------------+-----------+-----------------+
| Age Group | Driver Race | Violation | Violation Count |
+-----------+-------------+-----------+-----------------+
|   18-25   |    Asian    |  Speeding |       1740      |
|   18-25   |    Asian    |  Seatbelt |       1650      |
|   18-25   |    Asian    |   Other   |       1550      |
|   18-25   |    Asian    |    DUI    |       1510      |
|   18-25   |    Asian    |   Signal  |       1485      |
|   18-25   |    Black    |  Speeding |       1825      |
|   18-25   |    Black    |   Signal  |       1775      |
|   18-25   |    Black    |   Other   |       1660      |
|   18-25   |    Black    |    DUI    |       1565      |
|   18-25   |    Black    |  Seatbelt |       1525      |
|   18-25   |   Hispanic  |   Other   |       1710      |
|   18-25   |   Hispanic  |    DUI    |       1665      |
|   18-25   |   Hispanic  |  Seatbelt |       1560      |
|   18-25   |   Hispanic  |  Speeding |       1555      |
|   18-25   |   Hispanic  |   Signal  |       1535      |
|   18-25   |    Other    |  Seatbelt |       1745      |
|   18-25   |    Other    |  Speeding |       1660      |
|   18-25   |    Other    |   Signal  |       1650      |
|   18-25   |    Other    |   Other   |       1625      |
|   18-25   |    Other    |    DUI    |       1560      |
|   18-25   |    White    |   Signal  |       1735      |
|   18-25   |    White    |  Speeding |       1670      |
|   18-25   |    White    |   Other   |       1605      |
|   18-25   |    White    |  Seatbelt |       1580      |
|   18-25   |    White    |    DUI    |       1545      |
|   26-35   |    Asian    |   Signal  |       2215      |
|   26-35   |    Asian    |  Speeding |       2165      |
|   26-35   |    Asian    |    DUI    |       2115      |
|   26-35   |    Asian    |   Other   |       2105      |
|   26-35   |    Asian    |  Seatbelt |       2035      |
|   26-35   |    Black    |   Signal  |       2140      |
|   26-35   |    Black    |  Speeding |       2105      |
|   26-35   |    Black    |    DUI    |       2085      |
|   26-35   |    Black    |  Seatbelt |       2025      |
|   26-35   |    Black    |   Other   |       2010      |
|   26-35   |   Hispanic  |    DUI    |       2165      |
|   26-35   |   Hispanic  |  Seatbelt |       2130      |
|   26-35   |   Hispanic  |   Other   |       2065      |
|   26-35   |   Hispanic  |  Speeding |       2050      |
|   26-35   |   Hispanic  |   Signal  |       2010      |
|   26-35   |    Other    |  Speeding |       2205      |
|   26-35   |    Other    |    DUI    |       2155      |
|   26-35   |    Other    |  Seatbelt |       2020      |
|   26-35   |    Other    |   Other   |       2010      |
|   26-35   |    Other    |   Signal  |       1900      |
|   26-35   |    White    |   Signal  |       2175      |
|   26-35   |    White    |   Other   |       2065      |
|   26-35   |    White    |  Speeding |       2050      |
|   26-35   |    White    |  Seatbelt |       2020      |
|   26-35   |    White    |    DUI    |       1850      |
|   36-45   |    Asian    |    DUI    |       2200      |
|   36-45   |    Asian    |   Other   |       2170      |
|   36-45   |    Asian    |  Seatbelt |       2120      |
|   36-45   |    Asian    |   Signal  |       2090      |
|   36-45   |    Asian    |  Speeding |       2030      |
|   36-45   |    Black    |  Seatbelt |       2090      |
|   36-45   |    Black    |  Speeding |       2090      |
|   36-45   |    Black    |   Signal  |       2035      |
|   36-45   |    Black    |    DUI    |       2005      |
|   36-45   |    Black    |   Other   |       1980      |
|   36-45   |   Hispanic  |  Speeding |       2115      |
|   36-45   |   Hispanic  |  Seatbelt |       2105      |
|   36-45   |   Hispanic  |   Other   |       2070      |
|   36-45   |   Hispanic  |   Signal  |       2060      |
|   36-45   |   Hispanic  |    DUI    |       2000      |
|   36-45   |    Other    |  Seatbelt |       2190      |
|   36-45   |    Other    |   Other   |       2135      |
|   36-45   |    Other    |  Speeding |       2100      |
|   36-45   |    Other    |    DUI    |       2065      |
|   36-45   |    Other    |   Signal  |       2030      |
|   36-45   |    White    |   Signal  |       2255      |
|   36-45   |    White    |  Speeding |       2205      |
|   36-45   |    White    |  Seatbelt |       2155      |
|   36-45   |    White    |   Other   |       2095      |
|   36-45   |    White    |    DUI    |       2090      |
|   46-60   |    Asian    |   Signal  |       3145      |
|   46-60   |    Asian    |  Speeding |       3130      |
|   46-60   |    Asian    |  Seatbelt |       3085      |
|   46-60   |    Asian    |   Other   |       3070      |
|   46-60   |    Asian    |    DUI    |       3010      |
|   46-60   |    Black    |    DUI    |       3265      |
|   46-60   |    Black    |   Other   |       3260      |
|   46-60   |    Black    |  Seatbelt |       3230      |
|   46-60   |    Black    |  Speeding |       3200      |
|   46-60   |    Black    |   Signal  |       2920      |
|   46-60   |   Hispanic  |  Seatbelt |       3250      |
|   46-60   |   Hispanic  |   Other   |       3170      |
|   46-60   |   Hispanic  |   Signal  |       3145      |
|   46-60   |   Hispanic  |    DUI    |       3135      |
|   46-60   |   Hispanic  |  Speeding |       3020      |
|   46-60   |    Other    |   Signal  |       3260      |
|   46-60   |    Other    |    DUI    |       3160      |
|   46-60   |    Other    |  Seatbelt |       3150      |
|   46-60   |    Other    |   Other   |       3025      |
|   46-60   |    Other    |  Speeding |       2895      |
|   46-60   |    White    |   Other   |       3305      |
|   46-60   |    White    |  Speeding |       3235      |
|   46-60   |    White    |    DUI    |       3165      |
|   46-60   |    White    |   Signal  |       3135      |
|   46-60   |    White    |  Seatbelt |       2945      |
|    60+    |    Asian    |  Speeding |       4330      |
|    60+    |    Asian    |   Other   |       4320      |
|    60+    |    Asian    |    DUI    |       4230      |
|    60+    |    Asian    |   Signal  |       4165      |
|    60+    |    Asian    |  Seatbelt |       3890      |
|    60+    |    Black    |    DUI    |       4330      |
|    60+    |    Black    |   Other   |       4265      |
|    60+    |    Black    |   Signal  |       4140      |
|    60+    |    Black    |  Seatbelt |       4110      |
|    60+    |    Black    |  Speeding |       4020      |
|    60+    |   Hispanic  |   Signal  |       4225      |
|    60+    |   Hispanic  |   Other   |       4225      |
|    60+    |   Hispanic  |    DUI    |       4040      |
|    60+    |   Hispanic  |  Seatbelt |       4040      |
|    60+    |   Hispanic  |  Speeding |       3985      |
|    60+    |    Other    |   Other   |       4285      |
|    60+    |    Other    |  Seatbelt |       4280      |
|    60+    |    Other    |   Signal  |       4200      |
|    60+    |    Other    |    DUI    |       4160      |
|    60+    |    Other    |  Speeding |       4145      |
|    60+    |    White    |    DUI    |       4305      |
|    60+    |    White    |  Speeding |       4225      |
|    60+    |    White    |   Other   |       4190      |
|    60+    |    White    |   Signal  |       4135      |
|    60+    |    White    |  Seatbelt |       4105      |
+-----------+-------------+-----------+-----------------+

In [23]:
# 3.Time Period Analysis of Stops (Joining with Date Functions)

query = """
SELECT 
    t.country_name,
    CASE 
        WHEN HOUR(t.stop_time) BETWEEN 5 AND 11 THEN 'Morning'
        WHEN HOUR(t.stop_time) BETWEEN 12 AND 16 THEN 'Afternoon'
        WHEN HOUR(t.stop_time) BETWEEN 17 AND 20 THEN 'Evening'
        WHEN HOUR(t.stop_time) >= 21 OR HOUR(t.stop_time) <= 4 THEN 'Night'
        ELSE 'Unknown'
    END AS time_period,
    COUNT(*) AS stop_count
FROM traffic_stops t
WHERE t.stop_time IS NOT NULL
GROUP BY t.country_name, time_period
ORDER BY t.country_name, time_period;
"""

# Execute and fetch results
mycursor.execute(query)
results = mycursor.fetchall()

# Display results using PrettyTable
table = PrettyTable()
table.field_names = ["Country", "Time Period", "Stop Count"]

for row in results:
    table.add_row(row)

print(table)

+---------+-------------+------------+
| Country | Time Period | Stop Count |
+---------+-------------+------------+
|  Canada |  Afternoon  |   22605    |
|  Canada |   Evening   |   18025    |
|  Canada |   Morning   |   32735    |
|  Canada |    Night    |   36175    |
|  India  |  Afternoon  |   22685    |
|  India  |   Evening   |   18330    |
|  India  |   Morning   |   32115    |
|  India  |    Night    |   36860    |
|   USA   |  Afternoon  |   22300    |
|   USA   |   Evening   |   17645    |
|   USA   |   Morning   |   31750    |
|   USA   |    Night    |   36465    |
+---------+-------------+------------+

In [25]:
# 4.Correlation Between Age, Violation, and Stop Duration (Subquery)

query = """
SELECT 
    age_group,
    violation,
    stop_duration,
    COUNT(*) AS count
FROM (
    SELECT 
        CASE 
            WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
            WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
            WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
            WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
            WHEN driver_age > 60 THEN '60+'
            ELSE 'Unknown'
        END AS age_group,
        violation,
        stop_duration
    FROM traffic_stops
    WHERE driver_age IS NOT NULL AND violation IS NOT NULL AND stop_duration IS NOT NULL
) AS age_violation_data
GROUP BY age_group, violation, stop_duration
ORDER BY age_group, violation, stop_duration;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Display as table
table = PrettyTable()
table.field_names = ["Age Group", "Violation", "Stop Duration", "Count"]

for row in results:
    table.add_row(row)

print(table)

+-----------+-----------+---------------+-------+
| Age Group | Violation | Stop Duration | Count |
+-----------+-----------+---------------+-------+
|   18-25   |    DUI    |    0-15 Min   |  2470 |
|   18-25   |    DUI    |   16-30 Min   |  2685 |
|   18-25   |    DUI    |    30+ Min    |  2690 |
|   18-25   |   Other   |    0-15 Min   |  2645 |
|   18-25   |   Other   |   16-30 Min   |  2790 |
|   18-25   |   Other   |    30+ Min    |  2715 |
|   18-25   |  Seatbelt |    0-15 Min   |  2790 |
|   18-25   |  Seatbelt |   16-30 Min   |  2635 |
|   18-25   |  Seatbelt |    30+ Min    |  2635 |
|   18-25   |   Signal  |    0-15 Min   |  2750 |
|   18-25   |   Signal  |   16-30 Min   |  2805 |
|   18-25   |   Signal  |    30+ Min    |  2625 |
|   18-25   |  Speeding |    0-15 Min   |  2755 |
|   18-25   |  Speeding |   16-30 Min   |  2980 |
|   18-25   |  Speeding |    30+ Min    |  2715 |
|   26-35   |    DUI    |    0-15 Min   |  3505 |
|   26-35   |    DUI    |   16-30 Min   |  3420 |
|   26-35   |    DUI    |    30+ Min    |  3445 |
|   26-35   |   Other   |    0-15 Min   |  3280 |
|   26-35   |   Other   |   16-30 Min   |  3370 |
|   26-35   |   Other   |    30+ Min    |  3605 |
|   26-35   |  Seatbelt |    0-15 Min   |  3445 |
|   26-35   |  Seatbelt |   16-30 Min   |  3340 |
|   26-35   |  Seatbelt |    30+ Min    |  3445 |
|   26-35   |   Signal  |    0-15 Min   |  3420 |
|   26-35   |   Signal  |   16-30 Min   |  3320 |
|   26-35   |   Signal  |    30+ Min    |  3700 |
|   26-35   |  Speeding |    0-15 Min   |  3445 |
|   26-35   |  Speeding |   16-30 Min   |  3470 |
|   26-35   |  Speeding |    30+ Min    |  3660 |
|   36-45   |    DUI    |    0-15 Min   |  3580 |
|   36-45   |    DUI    |   16-30 Min   |  3495 |
|   36-45   |    DUI    |    30+ Min    |  3285 |
|   36-45   |   Other   |    0-15 Min   |  3595 |
|   36-45   |   Other   |   16-30 Min   |  3300 |
|   36-45   |   Other   |    30+ Min    |  3555 |
|   36-45   |  Seatbelt |    0-15 Min   |  3550 |
|   36-45   |  Seatbelt |   16-30 Min   |  3535 |
|   36-45   |  Seatbelt |    30+ Min    |  3575 |
|   36-45   |   Signal  |    0-15 Min   |  3525 |
|   36-45   |   Signal  |   16-30 Min   |  3570 |
|   36-45   |   Signal  |    30+ Min    |  3375 |
|   36-45   |  Speeding |    0-15 Min   |  3525 |
|   36-45   |  Speeding |   16-30 Min   |  3535 |
|   36-45   |  Speeding |    30+ Min    |  3480 |
|   46-60   |    DUI    |    0-15 Min   |  5360 |
|   46-60   |    DUI    |   16-30 Min   |  5205 |
|   46-60   |    DUI    |    30+ Min    |  5170 |
|   46-60   |   Other   |    0-15 Min   |  5140 |
|   46-60   |   Other   |   16-30 Min   |  5100 |
|   46-60   |   Other   |    30+ Min    |  5590 |
|   46-60   |  Seatbelt |    0-15 Min   |  5130 |
|   46-60   |  Seatbelt |   16-30 Min   |  5360 |
|   46-60   |  Seatbelt |    30+ Min    |  5170 |
|   46-60   |   Signal  |    0-15 Min   |  5170 |
|   46-60   |   Signal  |   16-30 Min   |  5270 |
|   46-60   |   Signal  |    30+ Min    |  5165 |
|   46-60   |  Speeding |    0-15 Min   |  5175 |
|   46-60   |  Speeding |   16-30 Min   |  5405 |
|   46-60   |  Speeding |    30+ Min    |  4900 |
|    60+    |    DUI    |    0-15 Min   |  7155 |
|    60+    |    DUI    |   16-30 Min   |  6850 |
|    60+    |    DUI    |    30+ Min    |  7060 |
|    60+    |   Other   |    0-15 Min   |  6665 |
|    60+    |   Other   |   16-30 Min   |  6920 |
|    60+    |   Other   |    30+ Min    |  7700 |
|    60+    |  Seatbelt |    0-15 Min   |  6800 |
|    60+    |  Seatbelt |   16-30 Min   |  6725 |
|    60+    |  Seatbelt |    30+ Min    |  6900 |
|    60+    |   Signal  |    0-15 Min   |  7305 |
|    60+    |   Signal  |   16-30 Min   |  6825 |
|    60+    |   Signal  |    30+ Min    |  6735 |
|    60+    |  Speeding |    0-15 Min   |  6975 |
|    60+    |  Speeding |   16-30 Min   |  6835 |
|    60+    |  Speeding |    30+ Min    |  6895 |
+-----------+-----------+---------------+-------+

In [27]:
# 5.Violations with High Search and Arrest Rates (Window Function)

query = """
SELECT 
    violation,
    total_stops,
    total_searches,
    total_arrests,
    ROUND((total_searches / total_stops) * 100, 2) AS search_rate_percent,
    ROUND((total_arrests / total_stops) * 100, 2) AS arrest_rate_percent,
    RANK() OVER (ORDER BY (total_searches / total_stops) DESC) AS search_rank,
    RANK() OVER (ORDER BY (total_arrests / total_stops) DESC) AS arrest_rank
FROM (
    SELECT 
        violation,
        COUNT(*) AS total_stops,
        SUM(CASE WHEN search_conducted = TRUE THEN 1 ELSE 0 END) AS total_searches,
        SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests
    FROM traffic_stops
    WHERE violation IS NOT NULL
    GROUP BY violation
) AS violation_stats
ORDER BY search_rate_percent DESC;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Display with PrettyTable
table = PrettyTable()
table.field_names = [
    "Violation", "Stops", "Searches", "Arrests", 
    "Search %", "Arrest %", "Search Rank", "Arrest Rank"
]

for row in results:
    table.add_row(row)

print(table)

+-----------+-------+----------+---------+----------+----------+-------------+-------------+
| Violation | Stops | Searches | Arrests | Search % | Arrest % | Search Rank | Arrest Rank |
+-----------+-------+----------+---------+----------+----------+-------------+-------------+
|  Seatbelt | 65035 |  32810   |  32865  |  50.45   |  50.53   |      1      |      2      |
|  Speeding | 65750 |  32865   |  32990  |  49.98   |  50.17   |      2      |      3      |
|   Other   | 65970 |  32880   |  32580  |  49.84   |  49.39   |      3      |      5      |
|   Signal  | 65560 |  32545   |  32745  |  49.64   |  49.95   |      4      |      4      |
|    DUI    | 65375 |  32405   |  33050  |  49.57   |  50.55   |      5      |      1      |
+-----------+-------+----------+---------+----------+----------+-------------+-------------+

In [38]:
# 6 Driver Demographics by Country (Age, Gender, and Race)

query = """
SELECT 
    country_name,
    driver_gender AS gender,
    driver_race AS race,
    CASE 
        WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
        WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
        WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
        WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
        WHEN driver_age > 60 THEN '60+'
        ELSE 'Unknown'
    END AS age_group,
    COUNT(*) AS total_drivers
FROM traffic_stops
WHERE driver_age IS NOT NULL
GROUP BY country_name, gender, race, age_group
ORDER BY country_name, gender, race, age_group;
"""

# Execute the query
mycursor.execute(query)

# Fetch the results
results = mycursor.fetchall()

# Create a PrettyTable object and set the column names
table = PrettyTable()
table.field_names = ["Country", "Gender", "Race", "Age Group", "Total Drivers"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+---------+--------+----------+-----------+---------------+
| Country | Gender |   Race   | Age Group | Total Drivers |
+---------+--------+----------+-----------+---------------+
|  Canada |   F    |  Asian   |   18-25   |      1420     |
|  Canada |   F    |  Asian   |   26-35   |      1745     |
|  Canada |   F    |  Asian   |   36-45   |      1720     |
|  Canada |   F    |  Asian   |   46-60   |      2550     |
|  Canada |   F    |  Asian   |    60+    |      3665     |
|  Canada |   F    |  Black   |   18-25   |      1335     |
|  Canada |   F    |  Black   |   26-35   |      1725     |
|  Canada |   F    |  Black   |   36-45   |      1625     |
|  Canada |   F    |  Black   |   46-60   |      2490     |
|  Canada |   F    |  Black   |    60+    |      3420     |
|  Canada |   F    | Hispanic |   18-25   |      1275     |
|  Canada |   F    | Hispanic |   26-35   |      1755     |
|  Canada |   F    | Hispanic |   36-45   |      1740     |
|  Canada |   F    | Hispanic |   46-60   |      2595     |
|  Canada |   F    | Hispanic |    60+    |      3590     |
|  Canada |   F    |  Other   |   18-25   |      1525     |
|  Canada |   F    |  Other   |   26-35   |      1645     |
|  Canada |   F    |  Other   |   36-45   |      1760     |
|  Canada |   F    |  Other   |   46-60   |      2585     |
|  Canada |   F    |  Other   |    60+    |      3590     |
|  Canada |   F    |  White   |   18-25   |      1375     |
|  Canada |   F    |  White   |   26-35   |      1720     |
|  Canada |   F    |  White   |   36-45   |      1850     |
|  Canada |   F    |  White   |   46-60   |      2790     |
|  Canada |   F    |  White   |    60+    |      3495     |
|  Canada |   M    |  Asian   |   18-25   |      1280     |
|  Canada |   M    |  Asian   |   26-35   |      1735     |
|  Canada |   M    |  Asian   |   36-45   |      1710     |
|  Canada |   M    |  Asian   |   46-60   |      2515     |
|  Canada |   M    |  Asian   |    60+    |      3380     |
|  Canada |   M    |  Black   |   18-25   |      1500     |
|  Canada |   M    |  Black   |   26-35   |      1730     |
|  Canada |   M    |  Black   |   36-45   |      1695     |
|  Canada |   M    |  Black   |   46-60   |      2680     |
|  Canada |   M    |  Black   |    60+    |      3510     |
|  Canada |   M    | Hispanic |   18-25   |      1400     |
|  Canada |   M    | Hispanic |   26-35   |      1835     |
|  Canada |   M    | Hispanic |   36-45   |      1865     |
|  Canada |   M    | Hispanic |   46-60   |      2590     |
|  Canada |   M    | Hispanic |    60+    |      3330     |
|  Canada |   M    |  Other   |   18-25   |      1320     |
|  Canada |   M    |  Other   |   26-35   |      1715     |
|  Canada |   M    |  Other   |   36-45   |      1785     |
|  Canada |   M    |  Other   |   46-60   |      2495     |
|  Canada |   M    |  Other   |    60+    |      3570     |
|  Canada |   M    |  White   |   18-25   |      1315     |
|  Canada |   M    |  White   |   26-35   |      1790     |
|  Canada |   M    |  White   |   36-45   |      1785     |
|  Canada |   M    |  White   |   46-60   |      2460     |
|  Canada |   M    |  White   |    60+    |      3565     |
|  India  |   F    |  Asian   |   18-25   |      1400     |
|  India  |   F    |  Asian   |   26-35   |      2025     |
|  India  |   F    |  Asian   |   36-45   |      1780     |
|  India  |   F    |  Asian   |   46-60   |      2710     |
|  India  |   F    |  Asian   |    60+    |      3495     |
|  India  |   F    |  Black   |   18-25   |      1310     |
|  India  |   F    |  Black   |   26-35   |      1800     |
|  India  |   F    |  Black   |   36-45   |      1705     |
|  India  |   F    |  Black   |   46-60   |      2845     |
|  India  |   F    |  Black   |    60+    |      3405     |
|  India  |   F    | Hispanic |   18-25   |      1295     |
|  India  |   F    | Hispanic |   26-35   |      1715     |
|  India  |   F    | Hispanic |   36-45   |      1760     |
|  India  |   F    | Hispanic |   46-60   |      2695     |
|  India  |   F    | Hispanic |    60+    |      3590     |
|  India  |   F    |  Other   |   18-25   |      1290     |
|  India  |   F    |  Other   |   26-35   |      1735     |
|  India  |   F    |  Other   |   36-45   |      1685     |
|  India  |   F    |  Other   |   46-60   |      2665     |
|  India  |   F    |  Other   |    60+    |      3515     |
|  India  |   F    |  White   |   18-25   |      1380     |
|  India  |   F    |  White   |   26-35   |      1645     |
|  India  |   F    |  White   |   36-45   |      1885     |
|  India  |   F    |  White   |   46-60   |      2640     |
|  India  |   F    |  White   |    60+    |      3245     |
|  India  |   M    |  Asian   |   18-25   |      1185     |
|  India  |   M    |  Asian   |   26-35   |      1775     |
|  India  |   M    |  Asian   |   36-45   |      1900     |
|  India  |   M    |  Asian   |   46-60   |      2535     |
|  India  |   M    |  Asian   |    60+    |      3450     |
|  India  |   M    |  Black   |   18-25   |      1365     |
|  India  |   M    |  Black   |   26-35   |      1740     |
|  India  |   M    |  Black   |   36-45   |      1605     |
|  India  |   M    |  Black   |   46-60   |      2665     |
|  India  |   M    |  Black   |    60+    |      3650     |
|  India  |   M    | Hispanic |   18-25   |      1420     |
|  India  |   M    | Hispanic |   26-35   |      1770     |
|  India  |   M    | Hispanic |   36-45   |      1590     |
|  India  |   M    | Hispanic |   46-60   |      2640     |
|  India  |   M    | Hispanic |    60+    |      3555     |
|  India  |   M    |  Other   |   18-25   |      1420     |
|  India  |   M    |  Other   |   26-35   |      1710     |
|  India  |   M    |  Other   |   36-45   |      1780     |
|  India  |   M    |  Other   |   46-60   |      2690     |
|  India  |   M    |  Other   |    60+    |      3395     |
|  India  |   M    |  White   |   18-25   |      1340     |
|  India  |   M    |  White   |   26-35   |      1735     |
|  India  |   M    |  White   |   36-45   |      1845     |
|  India  |   M    |  White   |   46-60   |      2505     |
|  India  |   M    |  White   |    60+    |      3510     |
|   USA   |   F    |  Asian   |   18-25   |      1300     |
|   USA   |   F    |  Asian   |   26-35   |      1670     |
|   USA   |   F    |  Asian   |   36-45   |      1830     |
|   USA   |   F    |  Asian   |   46-60   |      2375     |
|   USA   |   F    |  Asian   |    60+    |      3560     |
|   USA   |   F    |  Black   |   18-25   |      1360     |
|   USA   |   F    |  Black   |   26-35   |      1755     |
|   USA   |   F    |  Black   |   36-45   |      1885     |
|   USA   |   F    |  Black   |   46-60   |      2615     |
|   USA   |   F    |  Black   |    60+    |      3320     |
|   USA   |   F    | Hispanic |   18-25   |      1400     |
|   USA   |   F    | Hispanic |   26-35   |      1665     |
|   USA   |   F    | Hispanic |   36-45   |      1735     |
|   USA   |   F    | Hispanic |   46-60   |      2675     |
|   USA   |   F    | Hispanic |    60+    |      3350     |
|   USA   |   F    |  Other   |   18-25   |      1375     |
|   USA   |   F    |  Other   |   26-35   |      1625     |
|   USA   |   F    |  Other   |   36-45   |      1840     |
|   USA   |   F    |  Other   |   46-60   |      2435     |
|   USA   |   F    |  Other   |    60+    |      3350     |
|   USA   |   F    |  White   |   18-25   |      1450     |
|   USA   |   F    |  White   |   26-35   |      1620     |
|   USA   |   F    |  White   |   36-45   |      1665     |
|   USA   |   F    |  White   |   46-60   |      2750     |
|   USA   |   F    |  White   |    60+    |      3600     |
|   USA   |   M    |  Asian   |   18-25   |      1350     |
|   USA   |   M    |  Asian   |   26-35   |      1685     |
|   USA   |   M    |  Asian   |   36-45   |      1670     |
|   USA   |   M    |  Asian   |   46-60   |      2755     |
|   USA   |   M    |  Asian   |    60+    |      3385     |
|   USA   |   M    |  Black   |   18-25   |      1480     |
|   USA   |   M    |  Black   |   26-35   |      1615     |
|   USA   |   M    |  Black   |   36-45   |      1685     |
|   USA   |   M    |  Black   |   46-60   |      2580     |
|   USA   |   M    |  Black   |    60+    |      3560     |
|   USA   |   M    | Hispanic |   18-25   |      1235     |
|   USA   |   M    | Hispanic |   26-35   |      1680     |
|   USA   |   M    | Hispanic |   36-45   |      1660     |
|   USA   |   M    | Hispanic |   46-60   |      2525     |
|   USA   |   M    | Hispanic |    60+    |      3100     |
|   USA   |   M    |  Other   |   18-25   |      1310     |
|   USA   |   M    |  Other   |   26-35   |      1860     |
|   USA   |   M    |  Other   |   36-45   |      1670     |
|   USA   |   M    |  Other   |   46-60   |      2620     |
|   USA   |   M    |  Other   |    60+    |      3650     |
|   USA   |   M    |  White   |   18-25   |      1275     |
|   USA   |   M    |  White   |   26-35   |      1650     |
|   USA   |   M    |  White   |   36-45   |      1770     |
|   USA   |   M    |  White   |   46-60   |      2640     |
|   USA   |   M    |  White   |    60+    |      3545     |
+---------+--------+----------+-----------+---------------+

In [36]:
# 7.Top 5 Violations with Highest Arrest Rates

query = """
SELECT 
    violation,
    COUNT(*) AS total_stops,
    SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests,
    ROUND((SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS arrest_rate
FROM traffic_stops
GROUP BY violation
ORDER BY arrest_rate DESC
LIMIT 5;
"""

# Execute the query
mycursor.execute(query)

# Fetch the results
results = mycursor.fetchall()

# Create and display the table in a readable format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Total Stops", "Total Arrests", "Arrest Rate (%)"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+-----------+-------------+---------------+-----------------+
| Violation | Total Stops | Total Arrests | Arrest Rate (%) |
+-----------+-------------+---------------+-----------------+
|    DUI    |    65375    |     33050     |      50.55      |
|  Seatbelt |    65035    |     32865     |      50.53      |
|  Speeding |    65750    |     32990     |      50.17      |
|   Signal  |    65560    |     32745     |      49.95      |
|   Other   |    65970    |     32580     |      49.39      |
+-----------+-------------+---------------+-----------------+