In [274]:
import pandas as pd

In [276]:
import pandas as pd
df =pd.read_excel("maniproject2.xlsx")
df.head(30)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
5,2020-01-01,00:05:00,Canada,F,44,73,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,2020-01-01,00:06:00,USA,F,80,70,White,Signal Violation,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
7,2020-01-01,00:07:00,India,M,72,50,Asian,Drunk Driving,Other,False,NaN,Arrest,True,30+ Min,True,DL75KZ7835
8,2020-01-01,00:08:00,USA,F,80,30,Hispanic,Other,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
9,2020-01-01,00:09:00,USA,M,43,21,Asian,Signal Violation,Signal,True,NaN,Warning,True,16-30 Min,False,KA79RD2271
10,2020-01-01,00:10:00,India,F,66,76,Black,Speeding,Signal,False,NaN,Ticket,False,30+ Min,True,UP67CQ9426
11,2020-01-01,00:11:00,Canada,F,58,53,Hispanic,Signal Violation,Signal,False,Vehicle Search,Arrest,True,30+ Min,True,KA61JB1004
12,2020-01-01,00:12:00,India,M,51,46,Asian,Drunk Driving,Signal,False,Vehicle Search,Ticket,False,16-30 Min,True,WB70IV9884
13,2020-01-01,00:13:00,USA,M,55,58,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,WB56XQ8946
14,2020-01-01,00:14:00,India,M,44,25,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,GJ67CO6825
15,2020-01-01,00:15:00,USA,F,65,51,Hispanic,Other,DUI,True,Frisk,Ticket,False,16-30 Min,True,WB75TF1052
16,2020-01-01,00:16:00,India,M,75,21,Asian,Seatbelt,Speeding,True,Vehicle Search,Arrest,False,16-30 Min,False,UP82DB7554
17,2020-01-01,00:17:00,Canada,F,44,55,White,Signal Violation,Other,True,Vehicle Search,Warning,True,0-15 Min,True,MH15GS2782
18,2020-01-01,00:18:00,USA,M,46,71,White,Speeding,Speeding,True,Frisk,Warning,True,16-30 Min,True,MH80WR1351
19,2020-01-01,00:19:00,Canada,F,42,41,Hispanic,Signal Violation,Signal,False,NaN,Arrest,False,30+ Min,False,KA12GK6861
20,2020-01-01,00:20:00,USA,F,76,47,Hispanic,Signal Violation,Signal,False,NaN,Warning,False,0-15 Min,True,KA78HN8680
21,2020-01-01,00:21:00,Canada,F,56,25,Black,Other,DUI,True,Frisk,Arrest,False,0-15 Min,False,WB35BJ2947
22,2020-01-01,00:22:00,USA,F,25,59,Asian,Other,Speeding,False,NaN,Ticket,True,0-15 Min,True,GJ46IJ2247
23,2020-01-01,00:23:00,Canada,F,47,60,Black,Signal Violation,Signal,True,Frisk,Arrest,True,0-15 Min,False,GJ24GN5905
24,2020-01-01,00:24:00,India,M,33,76,Hispanic,Signal Violation,Speeding,False,NaN,Warning,False,16-30 Min,False,MH83XS7688
25,2020-01-01,00:25:00,USA,F,18,58,White,Other,Speeding,False,Frisk,Ticket,False,16-30 Min,True,KA95EW9912
26,2020-01-01,00:26:00,Canada,F,20,56,Asian,Drunk Driving,Other,False,NaN,Ticket,True,0-15 Min,False,DL36PY9336
27,2020-01-01,00:27:00,India,F,63,61,Other,Drunk Driving,Signal,True,Vehicle Search,Warning,False,0-15 Min,False,MH17TG9873
28,2020-01-01,00:28:00,USA,F,71,69,Hispanic,Seatbelt,Seatbelt,False,Vehicle Search,Ticket,True,0-15 Min,False,GJ67TR1208
29,2020-01-01,00:29:00,USA,M,51,39,Hispanic,Other,Seatbelt,True,Vehicle Search,Arrest,False,30+ Min,True,RJ65DM5842

In [278]:
df.shape

(65538, 16)

In [280]:
df.isnull().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [282]:
df['search_type'] = df['search_type'].ffill()

In [284]:
df.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [31]:
df.to_excel("cleaned_data.xlsx", index=False)

In [35]:
import os
os.getcwd()

'D:\\guvi data science'

In [43]:
folder_path = "D:/Users/YourUsername/Documents"
os.makedirs(folder_path, exist_ok=True)  # This will create the folder if it doesn't exist

file_path = os.path.join(folder_path, "cleaned_data.xlsx")
df.to_excel(file_path, index=False)

In [286]:
df.dtypes

stop_date             datetime64[ns]
stop_time                     object
country_name                  object
driver_gender                 object
driver_age_raw                 int64
driver_age                     int64
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
drugs_related_stop              bool
vehicle_number                object
dtype: object

In [266]:
import mysql.connector

mydb = mysql.connector.connect(
    host = "localhost",
    user = "mani",
    password="1234"
)

mycursor = mydb.cursor(buffered=True)

In [256]:
mycursor.execute("SHOW DATABASES")

for x in mycursor:
    print(x)

('information_schema',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('test',)

In [258]:
mycursor.execute("CREATE DATABASE police_post")

In [268]:
mycursor.execute("use police_post")

In [262]:
mycursor.execute("""
CREATE TABLE traffic_stops (
    stop_date DATE,
    stop_time TIME,
    country_name VARCHAR(80),
    driver_gender VARCHAR(1),
    driver_age_raw INT,
    driver_age INT,
    driver_race VARCHAR(50),
    violation_raw VARCHAR(100),
    violation VARCHAR(100),
    search_conducted BOOLEAN,
    search_type VARCHAR(100),
    stop_outcome VARCHAR(100),
    is_arrested FLOAT,
    stop_duration VARCHAR(50),
    drugs_related_stop BOOLEAN,
    vechicle_number VARCHAR(50)
)
""")

In [201]:
# batch_size = 200  # You can adjust this based on your machine

# for start in range(0, len(values), batch_size):
#     end = start + batch_size
#     batch = values[start:end]
#     mycursor.executemany(sql, batch)
#     mydb.commit()

In [270]:
# sql = """
# INSERT INTO traffic_stops (
#     stop_date, stop_time, country_name, driver_gender, driver_age_raw, driver_age, driver_race,
#     violation_raw, violation, search_conducted, search_type,
#     stop_outcome, is_arrested, stop_duration, drugs_related_stop, vechicle_number
# ) 
# VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
# """

# # Create list of tuples from DataFrame
# values = [
#     (
#         row.stop_date, row.stop_time, row.country_name, row.driver_gender,
#         row.driver_age_raw, row.driver_age, row.driver_race,
#         row.violation_raw, row.violation, row.search_conducted, row.search_type,
#         row.stop_outcome, row.is_arrested, row.stop_duration,
#         row.drugs_related_stop, row.vehicle_number
#     )
#     for index, row in df.iterrows()
# ]

# # Execute many
# mycursor.executemany(sql, values)
# mydb.commit()

In [288]:
df.shape

(65538, 16)

In [290]:
!pip install tabulate

from tabulate import tabulate

Requirement already satisfied: tabulate in c:\users\user\anaconda3\lib\site-packages (0.9.0)

In [291]:
# 1 Total Number of Police Stops
mycursor.execute("SELECT COUNT(*) AS total_police_stops FROM traffic_stops;")
out=mycursor.fetchall()
print(tabulate(out,headers=[i[0] for i in mycursor.description],  tablefmt='psql'))

+----------------------+
|   total_police_stops |
|----------------------|
|                65538 |
+----------------------+

In [294]:
# 2 Count of Stops by Violation Type

query = """
SELECT 
    violation,
    COUNT(*) AS stop_count
FROM 
    traffic_stops
GROUP BY 
    violation
ORDER BY 
    stop_count DESC;
"""

mycursor.execute(query)
results = mycursor.fetchall()

# Print results
for row in results:
    print(f"Violation: {row[0]}, Stops: {row[1]}")

Violation: Other, Stops: 13194
Violation: Speeding, Stops: 13150
Violation: Signal, Stops: 13112
Violation: DUI, Stops: 13075
Violation: Seatbelt, Stops: 13007

In [296]:
# 3 Number of Arrests vs. Warnings
query = """
SELECT 
    stop_outcome,
    COUNT(*) AS total
FROM 
    traffic_stops
WHERE 
    stop_outcome IN ('Arrest', 'Warning')
GROUP BY 
    stop_outcome
ORDER BY 
    total DESC;
"""

mycursor.execute(query)
results = mycursor.fetchall()

# Print results

for row in results:
    print(f"Stop Outcome: {row[0]}, Total: {row[1]}")

Stop Outcome: Warning, Total: 21966
Stop Outcome: Arrest, Total: 21734

In [298]:
# 4 Average Age of Drivers Stopped
query = """
SELECT 
    AVG(driver_age) AS average_driver_age
FROM 
    traffic_stops
WHERE 
    driver_age IS NOT NULL;
"""

mycursor.execute(query)
result = mycursor.fetchone()

print(f"Average Driver Age: {result[0]:.2f}")

Average Driver Age: 49.11

In [300]:
# 5 Top 5 Most Frequent Search Types

query = """
SELECT 
    search_type,
    COUNT(*) AS total_searches
FROM 
    traffic_stops
WHERE 
    search_type IS NOT NULL AND search_type != ''
GROUP BY 
    search_type
ORDER BY 
    total_searches DESC
LIMIT 5;
"""

mycursor.execute(query)
results = mycursor.fetchall()

# Print the results
for row in results:
    print(f"Search Type: {row[0]}, Total: {row[1]}")

Search Type: Frisk, Total: 32847
Search Type: Vehicle Search, Total: 32691

In [302]:
# 6 Count of Stops by Gender
!pip install prettytable
from prettytable import PrettyTable

query = """
SELECT 
    driver_gender,
    COUNT(*) AS total_stops
FROM 
    traffic_stops
WHERE 
    driver_gender IS NOT NULL
GROUP BY 
    driver_gender;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()
# Create and display the table
table = PrettyTable()
table.field_names = ["Driver Gender", "Total Stops"]

for row in results:
    table.add_row(row)

print(table)

Requirement already satisfied: prettytable in c:\users\user\anaconda3\lib\site-packages (3.16.0)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prettytable) (0.2.5)
+---------------+-------------+
| Driver Gender | Total Stops |
+---------------+-------------+
|       F       |    32881    |
|       M       |    32657    |
+---------------+-------------+

In [303]:
# 7 Most Common Violation for Arrests

query = """
SELECT 
    violation,
    COUNT(*) AS violation_count
FROM 
    traffic_stops
WHERE 
    is_arrested = 1
GROUP BY 
    violation
ORDER BY 
    violation_count DESC
LIMIT 1;
"""

# Execute the query
mycursor.execute(query)
result = mycursor.fetchone()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Violation Count"]

# Add the result row to the table
table.add_row(result)

# Print the table
print(table)

+-----------+-----------------+
| Violation | Violation Count |
+-----------+-----------------+
|    DUI    |       6610      |
+-----------+-----------------+

In [306]:
# 8 Average Stop Duration for Each Violation

query = """
SELECT 
    violation,
    AVG(stop_duration) AS average_stop_duration
FROM 
    traffic_stops
WHERE 
    stop_duration IS NOT NULL
GROUP BY 
    violation
ORDER BY 
    average_stop_duration DESC;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Average Stop Duration"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+-----------+-----------------------+
| Violation | Average Stop Duration |
+-----------+-----------------------+
|   Other   |   15.743974533879037  |
|  Seatbelt |   15.334358422387945  |
|  Speeding |   15.286692015209125  |
|    DUI    |   15.234875717017209  |
|   Signal  |    15.2019524100061   |
+-----------+-----------------------+

In [308]:
# 8 Average Stop Duration for Each Violation
query = """
SELECT 
    violation,
    ROUND(AVG(stop_duration), 2) AS average_stop_duration
FROM 
    traffic_stops
WHERE 
    stop_duration IS NOT NULL
GROUP BY 
    violation
ORDER BY 
    average_stop_duration DESC;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Average Stop Duration"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+-----------+-----------------------+
| Violation | Average Stop Duration |
+-----------+-----------------------+
|   Other   |         15.74         |
|  Seatbelt |         15.33         |
|  Speeding |         15.29         |
|    DUI    |         15.23         |
|   Signal  |          15.2         |
+-----------+-----------------------+

In [310]:
# 9 Number of Drug-Related Stops by Year

query = """
SELECT 
    YEAR(stop_date) AS stop_year,
    COUNT(*) AS drug_related_stops
FROM 
    traffic_stops
WHERE 
    drugs_related_stop = 1
GROUP BY 
    stop_year
ORDER BY 
    stop_year ASC;
"""

# Execute the query
mycursor.execute(query)
results = mycursor.fetchall()

# Create and display the table in boxed format using PrettyTable
table = PrettyTable()
table.field_names = ["Year", "Drug-Related Stops"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+------+--------------------+
| Year | Drug-Related Stops |
+------+--------------------+
| 2020 |       32769        |
+------+--------------------+

In [312]:
# 10 Drivers with the Highest Number of Stops
sql = """
SELECT vechicle_number, COUNT(*) AS stop_count
FROM traffic_stops
GROUP BY vechicle_number
ORDER BY stop_count DESC
LIMIT 10;
"""

mycursor.execute(sql)
results = mycursor.fetchall()

# Convert to pandas DataFrame
df_top = pd.DataFrame(results, columns=["Vehicle Number", "Stop Count"])

# Print as a nice table
print(tabulate(df_top, headers='keys', tablefmt='psql', showindex=False))

+------------------+--------------+
| Vehicle Number   |   Stop Count |
|------------------+--------------|
| KA43LU7406       |            1 |
| UP32KI1335       |            1 |
| RJ29GT2317       |            1 |
| WB33TW1262       |            1 |
| KA59ZA1367       |            1 |
| UP30FF9970       |            1 |
| RJ10CT6132       |            1 |
| UP35RW2250       |            1 |
| MH64AV9856       |            1 |
| UP49FW2306       |            1 |
+------------------+--------------+

In [314]:
# 11 Number of Stops Conducted at Night (Between 10 PM - 5 AM)
sql = """
SELECT 
    COUNT(*) AS night_stops
FROM 
    traffic_stops
WHERE 
    (stop_time >= '22:00:00' OR stop_time <= '05:00:00');
"""

# Execute the query
mycursor.execute(sql)
result = mycursor.fetchone()

# Display the result
night_stops = result[0]
print(f"Number of Stops Conducted at Night (Between 10 PM - 5 AM): {night_stops}")

Number of Stops Conducted at Night (Between 10 PM - 5 AM): 19246

In [316]:
# 12. Number of Searches Conducted by Violation Type

sql = """
SELECT 
    violation, 
    COUNT(*) AS search_count
FROM 
    traffic_stops
WHERE 
    search_conducted = 1
GROUP BY 
    violation
ORDER BY 
    search_count DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Violation Type", "Search Count"]

# Add rows to the table
for row in results:
    table.add_row(row)
# Print the table
print(table)

+----------------+--------------+
| Violation Type | Search Count |
+----------------+--------------+
|     Other      |     6576     |
|    Speeding    |     6573     |
|    Seatbelt    |     6562     |
|     Signal     |     6509     |
|      DUI       |     6481     |
+----------------+--------------+

In [318]:
# 13. Arrest Rate by Driver Gender

sql = """
SELECT 
    driver_gender,
    COUNT(*) AS total_stops,
    SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests,
    (SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS arrest_rate
FROM 
    traffic_stops
GROUP BY 
    driver_gender
ORDER BY 
    arrest_rate DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Driver Gender", "Total Stops", "Total Arrests", "Arrest Rate (%)"]

# Add rows to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+---------------+-------------+---------------+-----------------+
| Driver Gender | Total Stops | Total Arrests | Arrest Rate (%) |
+---------------+-------------+---------------+-----------------+
|       F       |    32881    |     16553     |     50.3421     |
|       M       |    32657    |     16293     |     49.8913     |
+---------------+-------------+---------------+-----------------+

In [320]:
# 14. Violation Trends Over Time (Monthly Count of Violations)

sql = """
SELECT 
    YEAR(stop_date) AS violation_year,
    MONTH(stop_date) AS violation_month,
    violation,
    COUNT(*) AS violation_count
FROM 
    traffic_stops
GROUP BY 
    violation_year, violation_month, violation
ORDER BY 
    violation_year, violation_month, violation_count DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Year", "Month", "Violation", "Violation Count"]

# Add rows to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+------+-------+-----------+-----------------+
| Year | Month | Violation | Violation Count |
+------+-------+-----------+-----------------+
| 2020 |   1   |   Other   |       8970      |
| 2020 |   1   |  Speeding |       8942      |
| 2020 |   1   |   Signal  |       8923      |
| 2020 |   1   |    DUI    |       8906      |
| 2020 |   1   |  Seatbelt |       8899      |
| 2020 |   2   |   Other   |       4224      |
| 2020 |   2   |  Speeding |       4208      |
| 2020 |   2   |   Signal  |       4189      |
| 2020 |   2   |    DUI    |       4169      |
| 2020 |   2   |  Seatbelt |       4108      |
+------+-------+-----------+-----------------+

In [322]:
# 15.Most Common Stop Outcomes for Drug-Related Stops

sql = """
SELECT 
    stop_outcome,
    COUNT(*) AS outcome_count
FROM 
    traffic_stops
WHERE 
    drugs_related_stop = 1
GROUP BY 
    stop_outcome
ORDER BY 
    outcome_count DESC;
"""

# Execute the query
mycursor.execute(sql)
results = mycursor.fetchall()

# Create PrettyTable object to display the result in a table format
table = PrettyTable()
table.field_names = ["Stop Outcome", "Outcome Count"]

# Add rows to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+--------------+---------------+
| Stop Outcome | Outcome Count |
+--------------+---------------+
|   Warning    |     11058     |
|    Arrest    |     10869     |
|    Ticket    |     10842     |
+--------------+---------------+

Complex questions

In [325]:
# 1.Yearly Breakdown of Stops and Arrests by Country (Using Subquery and Window Functions)

query = """
SELECT 
    country_name,
    stop_year,
    total_stops,
    total_arrests,
    SUM(total_arrests) OVER (PARTITION BY country_name ORDER BY stop_year) AS cumulative_arrests
FROM (
    SELECT 
        country_name,
        YEAR(stop_date) AS stop_year,
        COUNT(*) AS total_stops,
        SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests
    FROM traffic_stops
    GROUP BY country_name, YEAR(stop_date)
) AS yearly_data
ORDER BY country_name, stop_year;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Setup PrettyTable
table = PrettyTable()
table.field_names = ["Country", "Year", "Total Stops", "Total Arrests", "Cumulative Arrests"]

for row in results:
    table.add_row(row)

# Print the formatted table
print(table)

+---------+------+-------------+---------------+--------------------+
| Country | Year | Total Stops | Total Arrests | Cumulative Arrests |
+---------+------+-------------+---------------+--------------------+
|  Canada | 2020 |    21908    |     10999     |       10999        |
|  India  | 2020 |    21998    |     11091     |       11091        |
|   USA   | 2020 |    21632    |     10756     |       10756        |
+---------+------+-------------+---------------+--------------------+

In [327]:

# query = """
# SELECT 
#     v.age_group,
#     t.driver_race,
#     t.violation,
#     COUNT(*) AS violation_count
# FROM (
#     SELECT 
#         driver_age,
#         CASE 
#             WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
#             WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
#             WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
#             WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
#             WHEN driver_age > 60 THEN '60+'
#             ELSE 'Unknown'
#         END AS age_group
#     FROM traffic_stops
# ) AS v
# JOIN traffic_stops t ON v.driver_age = t.driver_age
# GROUP BY v.age_group, t.driver_race, t.violation
# ORDER BY v.age_group, t.driver_race, violation_count DESC;
# """

# # Execute and fetch
# mycursor.execute(query)
# results = mycursor.fetchall()

# # Display in table
# table = PrettyTable()
# table.field_names = ["Age Group", "Driver Race", "Violation", "Violation Count"]

# for row in results:
#     table.add_row(row)

# print(table)

In [329]:
# 2.Driver Violation Trends Based on Age and Race (Join with Subquery)

query = """
SELECT 
    CASE 
        WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
        WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
        WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
        WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
        WHEN driver_age > 60 THEN '60+'
        ELSE 'Unknown'
    END AS age_group,
    driver_race,
    violation,
    COUNT(*) AS violation_count
FROM traffic_stops
WHERE driver_age IS NOT NULL
GROUP BY age_group, driver_race, violation
ORDER BY age_group, driver_race, violation_count DESC;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Display with PrettyTable
table = PrettyTable()
table.field_names = ["Age Group", "Driver Race", "Violation", "Violation Count"]

for row in results:
    table.add_row(row)

print(table)

+-----------+-------------+-----------+-----------------+
| Age Group | Driver Race | Violation | Violation Count |
+-----------+-------------+-----------+-----------------+
|   18-25   |    Asian    |  Speeding |       348       |
|   18-25   |    Asian    |  Seatbelt |       330       |
|   18-25   |    Asian    |   Other   |       310       |
|   18-25   |    Asian    |    DUI    |       302       |
|   18-25   |    Asian    |   Signal  |       297       |
|   18-25   |    Black    |  Speeding |       365       |
|   18-25   |    Black    |   Signal  |       355       |
|   18-25   |    Black    |   Other   |       332       |
|   18-25   |    Black    |    DUI    |       313       |
|   18-25   |    Black    |  Seatbelt |       305       |
|   18-25   |   Hispanic  |   Other   |       342       |
|   18-25   |   Hispanic  |    DUI    |       333       |
|   18-25   |   Hispanic  |  Seatbelt |       312       |
|   18-25   |   Hispanic  |  Speeding |       311       |
|   18-25   |   Hispanic  |   Signal  |       307       |
|   18-25   |    Other    |  Seatbelt |       349       |
|   18-25   |    Other    |  Speeding |       332       |
|   18-25   |    Other    |   Signal  |       330       |
|   18-25   |    Other    |   Other   |       325       |
|   18-25   |    Other    |    DUI    |       312       |
|   18-25   |    White    |   Signal  |       347       |
|   18-25   |    White    |  Speeding |       334       |
|   18-25   |    White    |   Other   |       321       |
|   18-25   |    White    |  Seatbelt |       316       |
|   18-25   |    White    |    DUI    |       309       |
|   26-35   |    Asian    |   Signal  |       443       |
|   26-35   |    Asian    |  Speeding |       433       |
|   26-35   |    Asian    |    DUI    |       423       |
|   26-35   |    Asian    |   Other   |       421       |
|   26-35   |    Asian    |  Seatbelt |       407       |
|   26-35   |    Black    |   Signal  |       428       |
|   26-35   |    Black    |  Speeding |       421       |
|   26-35   |    Black    |    DUI    |       417       |
|   26-35   |    Black    |  Seatbelt |       405       |
|   26-35   |    Black    |   Other   |       402       |
|   26-35   |   Hispanic  |    DUI    |       433       |
|   26-35   |   Hispanic  |  Seatbelt |       426       |
|   26-35   |   Hispanic  |   Other   |       413       |
|   26-35   |   Hispanic  |  Speeding |       410       |
|   26-35   |   Hispanic  |   Signal  |       402       |
|   26-35   |    Other    |  Speeding |       441       |
|   26-35   |    Other    |    DUI    |       431       |
|   26-35   |    Other    |  Seatbelt |       404       |
|   26-35   |    Other    |   Other   |       402       |
|   26-35   |    Other    |   Signal  |       380       |
|   26-35   |    White    |   Signal  |       435       |
|   26-35   |    White    |   Other   |       413       |
|   26-35   |    White    |  Speeding |       410       |
|   26-35   |    White    |  Seatbelt |       404       |
|   26-35   |    White    |    DUI    |       370       |
|   36-45   |    Asian    |    DUI    |       440       |
|   36-45   |    Asian    |   Other   |       434       |
|   36-45   |    Asian    |  Seatbelt |       424       |
|   36-45   |    Asian    |   Signal  |       418       |
|   36-45   |    Asian    |  Speeding |       406       |
|   36-45   |    Black    |  Seatbelt |       418       |
|   36-45   |    Black    |  Speeding |       418       |
|   36-45   |    Black    |   Signal  |       407       |
|   36-45   |    Black    |    DUI    |       401       |
|   36-45   |    Black    |   Other   |       396       |
|   36-45   |   Hispanic  |  Speeding |       423       |
|   36-45   |   Hispanic  |  Seatbelt |       421       |
|   36-45   |   Hispanic  |   Other   |       414       |
|   36-45   |   Hispanic  |   Signal  |       412       |
|   36-45   |   Hispanic  |    DUI    |       400       |
|   36-45   |    Other    |  Seatbelt |       438       |
|   36-45   |    Other    |   Other   |       427       |
|   36-45   |    Other    |  Speeding |       420       |
|   36-45   |    Other    |    DUI    |       413       |
|   36-45   |    Other    |   Signal  |       406       |
|   36-45   |    White    |   Signal  |       451       |
|   36-45   |    White    |  Speeding |       441       |
|   36-45   |    White    |  Seatbelt |       431       |
|   36-45   |    White    |   Other   |       419       |
|   36-45   |    White    |    DUI    |       418       |
|   46-60   |    Asian    |   Signal  |       629       |
|   46-60   |    Asian    |  Speeding |       626       |
|   46-60   |    Asian    |  Seatbelt |       617       |
|   46-60   |    Asian    |   Other   |       614       |
|   46-60   |    Asian    |    DUI    |       602       |
|   46-60   |    Black    |    DUI    |       653       |
|   46-60   |    Black    |   Other   |       652       |
|   46-60   |    Black    |  Seatbelt |       646       |
|   46-60   |    Black    |  Speeding |       640       |
|   46-60   |    Black    |   Signal  |       584       |
|   46-60   |   Hispanic  |  Seatbelt |       650       |
|   46-60   |   Hispanic  |   Other   |       634       |
|   46-60   |   Hispanic  |   Signal  |       629       |
|   46-60   |   Hispanic  |    DUI    |       627       |
|   46-60   |   Hispanic  |  Speeding |       604       |
|   46-60   |    Other    |   Signal  |       652       |
|   46-60   |    Other    |    DUI    |       632       |
|   46-60   |    Other    |  Seatbelt |       630       |
|   46-60   |    Other    |   Other   |       605       |
|   46-60   |    Other    |  Speeding |       579       |
|   46-60   |    White    |   Other   |       661       |
|   46-60   |    White    |  Speeding |       647       |
|   46-60   |    White    |    DUI    |       633       |
|   46-60   |    White    |   Signal  |       627       |
|   46-60   |    White    |  Seatbelt |       589       |
|    60+    |    Asian    |  Speeding |       866       |
|    60+    |    Asian    |   Other   |       864       |
|    60+    |    Asian    |    DUI    |       846       |
|    60+    |    Asian    |   Signal  |       833       |
|    60+    |    Asian    |  Seatbelt |       778       |
|    60+    |    Black    |    DUI    |       866       |
|    60+    |    Black    |   Other   |       853       |
|    60+    |    Black    |   Signal  |       828       |
|    60+    |    Black    |  Seatbelt |       822       |
|    60+    |    Black    |  Speeding |       804       |
|    60+    |   Hispanic  |   Signal  |       845       |
|    60+    |   Hispanic  |   Other   |       845       |
|    60+    |   Hispanic  |    DUI    |       808       |
|    60+    |   Hispanic  |  Seatbelt |       808       |
|    60+    |   Hispanic  |  Speeding |       797       |
|    60+    |    Other    |   Other   |       857       |
|    60+    |    Other    |  Seatbelt |       856       |
|    60+    |    Other    |   Signal  |       840       |
|    60+    |    Other    |    DUI    |       832       |
|    60+    |    Other    |  Speeding |       829       |
|    60+    |    White    |    DUI    |       861       |
|    60+    |    White    |  Speeding |       845       |
|    60+    |    White    |   Other   |       838       |
|    60+    |    White    |   Signal  |       827       |
|    60+    |    White    |  Seatbelt |       821       |
+-----------+-------------+-----------+-----------------+

In [331]:
# 3.Time Period Analysis of Stops (Joining with Date Functions)

query = """
SELECT 
    t.country_name,
    CASE 
        WHEN HOUR(t.stop_time) BETWEEN 5 AND 11 THEN 'Morning'
        WHEN HOUR(t.stop_time) BETWEEN 12 AND 16 THEN 'Afternoon'
        WHEN HOUR(t.stop_time) BETWEEN 17 AND 20 THEN 'Evening'
        WHEN HOUR(t.stop_time) >= 21 OR HOUR(t.stop_time) <= 4 THEN 'Night'
        ELSE 'Unknown'
    END AS time_period,
    COUNT(*) AS stop_count
FROM traffic_stops t
WHERE t.stop_time IS NOT NULL
GROUP BY t.country_name, time_period
ORDER BY t.country_name, time_period;
"""

# Execute and fetch results
mycursor.execute(query)
results = mycursor.fetchall()

# Display results using PrettyTable
table = PrettyTable()
table.field_names = ["Country", "Time Period", "Stop Count"]

for row in results:
    table.add_row(row)

print(table)

+---------+-------------+------------+
| Country | Time Period | Stop Count |
+---------+-------------+------------+
|  Canada |  Afternoon  |    4521    |
|  Canada |   Evening   |    3605    |
|  Canada |   Morning   |    6547    |
|  Canada |    Night    |    7235    |
|  India  |  Afternoon  |    4537    |
|  India  |   Evening   |    3666    |
|  India  |   Morning   |    6423    |
|  India  |    Night    |    7372    |
|   USA   |  Afternoon  |    4460    |
|   USA   |   Evening   |    3529    |
|   USA   |   Morning   |    6350    |
|   USA   |    Night    |    7293    |
+---------+-------------+------------+

In [333]:
# 4.Correlation Between Age, Violation, and Stop Duration (Subquery)

query = """
SELECT 
    age_group,
    violation,
    stop_duration,
    COUNT(*) AS count
FROM (
    SELECT 
        CASE 
            WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
            WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
            WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
            WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
            WHEN driver_age > 60 THEN '60+'
            ELSE 'Unknown'
        END AS age_group,
        violation,
        stop_duration
    FROM traffic_stops
    WHERE driver_age IS NOT NULL AND violation IS NOT NULL AND stop_duration IS NOT NULL
) AS age_violation_data
GROUP BY age_group, violation, stop_duration
ORDER BY age_group, violation, stop_duration;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Display as table
table = PrettyTable()
table.field_names = ["Age Group", "Violation", "Stop Duration", "Count"]

for row in results:
    table.add_row(row)

print(table)

+-----------+-----------+---------------+-------+
| Age Group | Violation | Stop Duration | Count |
+-----------+-----------+---------------+-------+
|   18-25   |    DUI    |    0-15 Min   |  494  |
|   18-25   |    DUI    |   16-30 Min   |  537  |
|   18-25   |    DUI    |    30+ Min    |  538  |
|   18-25   |   Other   |    0-15 Min   |  529  |
|   18-25   |   Other   |   16-30 Min   |  558  |
|   18-25   |   Other   |    30+ Min    |  543  |
|   18-25   |  Seatbelt |    0-15 Min   |  558  |
|   18-25   |  Seatbelt |   16-30 Min   |  527  |
|   18-25   |  Seatbelt |    30+ Min    |  527  |
|   18-25   |   Signal  |    0-15 Min   |  550  |
|   18-25   |   Signal  |   16-30 Min   |  561  |
|   18-25   |   Signal  |    30+ Min    |  525  |
|   18-25   |  Speeding |    0-15 Min   |  551  |
|   18-25   |  Speeding |   16-30 Min   |  596  |
|   18-25   |  Speeding |    30+ Min    |  543  |
|   26-35   |    DUI    |    0-15 Min   |  701  |
|   26-35   |    DUI    |   16-30 Min   |  684  |
|   26-35   |    DUI    |    30+ Min    |  689  |
|   26-35   |   Other   |    0-15 Min   |  656  |
|   26-35   |   Other   |   16-30 Min   |  674  |
|   26-35   |   Other   |    30+ Min    |  721  |
|   26-35   |  Seatbelt |    0-15 Min   |  689  |
|   26-35   |  Seatbelt |   16-30 Min   |  668  |
|   26-35   |  Seatbelt |    30+ Min    |  689  |
|   26-35   |   Signal  |    0-15 Min   |  684  |
|   26-35   |   Signal  |   16-30 Min   |  664  |
|   26-35   |   Signal  |    30+ Min    |  740  |
|   26-35   |  Speeding |    0-15 Min   |  689  |
|   26-35   |  Speeding |   16-30 Min   |  694  |
|   26-35   |  Speeding |    30+ Min    |  732  |
|   36-45   |    DUI    |    0-15 Min   |  716  |
|   36-45   |    DUI    |   16-30 Min   |  699  |
|   36-45   |    DUI    |    30+ Min    |  657  |
|   36-45   |   Other   |    0-15 Min   |  719  |
|   36-45   |   Other   |   16-30 Min   |  660  |
|   36-45   |   Other   |    30+ Min    |  711  |
|   36-45   |  Seatbelt |    0-15 Min   |  710  |
|   36-45   |  Seatbelt |   16-30 Min   |  707  |
|   36-45   |  Seatbelt |    30+ Min    |  715  |
|   36-45   |   Signal  |    0-15 Min   |  705  |
|   36-45   |   Signal  |   16-30 Min   |  714  |
|   36-45   |   Signal  |    30+ Min    |  675  |
|   36-45   |  Speeding |    0-15 Min   |  705  |
|   36-45   |  Speeding |   16-30 Min   |  707  |
|   36-45   |  Speeding |    30+ Min    |  696  |
|   46-60   |    DUI    |    0-15 Min   |  1072 |
|   46-60   |    DUI    |   16-30 Min   |  1041 |
|   46-60   |    DUI    |    30+ Min    |  1034 |
|   46-60   |   Other   |    0-15 Min   |  1028 |
|   46-60   |   Other   |   16-30 Min   |  1020 |
|   46-60   |   Other   |    30+ Min    |  1118 |
|   46-60   |  Seatbelt |    0-15 Min   |  1026 |
|   46-60   |  Seatbelt |   16-30 Min   |  1072 |
|   46-60   |  Seatbelt |    30+ Min    |  1034 |
|   46-60   |   Signal  |    0-15 Min   |  1034 |
|   46-60   |   Signal  |   16-30 Min   |  1054 |
|   46-60   |   Signal  |    30+ Min    |  1033 |
|   46-60   |  Speeding |    0-15 Min   |  1035 |
|   46-60   |  Speeding |   16-30 Min   |  1081 |
|   46-60   |  Speeding |    30+ Min    |  980  |
|    60+    |    DUI    |    0-15 Min   |  1431 |
|    60+    |    DUI    |   16-30 Min   |  1370 |
|    60+    |    DUI    |    30+ Min    |  1412 |
|    60+    |   Other   |    0-15 Min   |  1333 |
|    60+    |   Other   |   16-30 Min   |  1384 |
|    60+    |   Other   |    30+ Min    |  1540 |
|    60+    |  Seatbelt |    0-15 Min   |  1360 |
|    60+    |  Seatbelt |   16-30 Min   |  1345 |
|    60+    |  Seatbelt |    30+ Min    |  1380 |
|    60+    |   Signal  |    0-15 Min   |  1461 |
|    60+    |   Signal  |   16-30 Min   |  1365 |
|    60+    |   Signal  |    30+ Min    |  1347 |
|    60+    |  Speeding |    0-15 Min   |  1395 |
|    60+    |  Speeding |   16-30 Min   |  1367 |
|    60+    |  Speeding |    30+ Min    |  1379 |
+-----------+-----------+---------------+-------+

In [335]:
# 5.Violations with High Search and Arrest Rates (Window Function)

query = """
SELECT 
    violation,
    total_stops,
    total_searches,
    total_arrests,
    ROUND((total_searches / total_stops) * 100, 2) AS search_rate_percent,
    ROUND((total_arrests / total_stops) * 100, 2) AS arrest_rate_percent,
    RANK() OVER (ORDER BY (total_searches / total_stops) DESC) AS search_rank,
    RANK() OVER (ORDER BY (total_arrests / total_stops) DESC) AS arrest_rank
FROM (
    SELECT 
        violation,
        COUNT(*) AS total_stops,
        SUM(CASE WHEN search_conducted = TRUE THEN 1 ELSE 0 END) AS total_searches,
        SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests
    FROM traffic_stops
    WHERE violation IS NOT NULL
    GROUP BY violation
) AS violation_stats
ORDER BY search_rate_percent DESC;
"""

# Execute and fetch
mycursor.execute(query)
results = mycursor.fetchall()

# Display with PrettyTable
table = PrettyTable()
table.field_names = [
    "Violation", "Stops", "Searches", "Arrests", 
    "Search %", "Arrest %", "Search Rank", "Arrest Rank"
]

for row in results:
    table.add_row(row)

print(table)

+-----------+-------+----------+---------+----------+----------+-------------+-------------+
| Violation | Stops | Searches | Arrests | Search % | Arrest % | Search Rank | Arrest Rank |
+-----------+-------+----------+---------+----------+----------+-------------+-------------+
|  Seatbelt | 13007 |   6562   |   6573  |  50.45   |  50.53   |      1      |      2      |
|  Speeding | 13150 |   6573   |   6598  |  49.98   |  50.17   |      2      |      3      |
|   Other   | 13194 |   6576   |   6516  |  49.84   |  49.39   |      3      |      5      |
|   Signal  | 13112 |   6509   |   6549  |  49.64   |  49.95   |      4      |      4      |
|    DUI    | 13075 |   6481   |   6610  |  49.57   |  50.55   |      5      |      1      |
+-----------+-------+----------+---------+----------+----------+-------------+-------------+

In [337]:
# 6 Driver Demographics by Country (Age, Gender, and Race)

query = """
SELECT 
    country_name,
    driver_gender AS gender,
    driver_race AS race,
    CASE 
        WHEN driver_age BETWEEN 18 AND 25 THEN '18-25'
        WHEN driver_age BETWEEN 26 AND 35 THEN '26-35'
        WHEN driver_age BETWEEN 36 AND 45 THEN '36-45'
        WHEN driver_age BETWEEN 46 AND 60 THEN '46-60'
        WHEN driver_age > 60 THEN '60+'
        ELSE 'Unknown'
    END AS age_group,
    COUNT(*) AS total_drivers
FROM traffic_stops
WHERE driver_age IS NOT NULL
GROUP BY country_name, gender, race, age_group
ORDER BY country_name, gender, race, age_group;
"""

# Execute the query
mycursor.execute(query)

# Fetch the results
results = mycursor.fetchall()

# Create a PrettyTable object and set the column names
table = PrettyTable()
table.field_names = ["Country", "Gender", "Race", "Age Group", "Total Drivers"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+---------+--------+----------+-----------+---------------+
| Country | Gender |   Race   | Age Group | Total Drivers |
+---------+--------+----------+-----------+---------------+
|  Canada |   F    |  Asian   |   18-25   |      284      |
|  Canada |   F    |  Asian   |   26-35   |      349      |
|  Canada |   F    |  Asian   |   36-45   |      344      |
|  Canada |   F    |  Asian   |   46-60   |      510      |
|  Canada |   F    |  Asian   |    60+    |      733      |
|  Canada |   F    |  Black   |   18-25   |      267      |
|  Canada |   F    |  Black   |   26-35   |      345      |
|  Canada |   F    |  Black   |   36-45   |      325      |
|  Canada |   F    |  Black   |   46-60   |      498      |
|  Canada |   F    |  Black   |    60+    |      684      |
|  Canada |   F    | Hispanic |   18-25   |      255      |
|  Canada |   F    | Hispanic |   26-35   |      351      |
|  Canada |   F    | Hispanic |   36-45   |      348      |
|  Canada |   F    | Hispanic |   46-60   |      519      |
|  Canada |   F    | Hispanic |    60+    |      718      |
|  Canada |   F    |  Other   |   18-25   |      305      |
|  Canada |   F    |  Other   |   26-35   |      329      |
|  Canada |   F    |  Other   |   36-45   |      352      |
|  Canada |   F    |  Other   |   46-60   |      517      |
|  Canada |   F    |  Other   |    60+    |      718      |
|  Canada |   F    |  White   |   18-25   |      275      |
|  Canada |   F    |  White   |   26-35   |      344      |
|  Canada |   F    |  White   |   36-45   |      370      |
|  Canada |   F    |  White   |   46-60   |      558      |
|  Canada |   F    |  White   |    60+    |      699      |
|  Canada |   M    |  Asian   |   18-25   |      256      |
|  Canada |   M    |  Asian   |   26-35   |      347      |
|  Canada |   M    |  Asian   |   36-45   |      342      |
|  Canada |   M    |  Asian   |   46-60   |      503      |
|  Canada |   M    |  Asian   |    60+    |      676      |
|  Canada |   M    |  Black   |   18-25   |      300      |
|  Canada |   M    |  Black   |   26-35   |      346      |
|  Canada |   M    |  Black   |   36-45   |      339      |
|  Canada |   M    |  Black   |   46-60   |      536      |
|  Canada |   M    |  Black   |    60+    |      702      |
|  Canada |   M    | Hispanic |   18-25   |      280      |
|  Canada |   M    | Hispanic |   26-35   |      367      |
|  Canada |   M    | Hispanic |   36-45   |      373      |
|  Canada |   M    | Hispanic |   46-60   |      518      |
|  Canada |   M    | Hispanic |    60+    |      666      |
|  Canada |   M    |  Other   |   18-25   |      264      |
|  Canada |   M    |  Other   |   26-35   |      343      |
|  Canada |   M    |  Other   |   36-45   |      357      |
|  Canada |   M    |  Other   |   46-60   |      499      |
|  Canada |   M    |  Other   |    60+    |      714      |
|  Canada |   M    |  White   |   18-25   |      263      |
|  Canada |   M    |  White   |   26-35   |      358      |
|  Canada |   M    |  White   |   36-45   |      357      |
|  Canada |   M    |  White   |   46-60   |      492      |
|  Canada |   M    |  White   |    60+    |      713      |
|  India  |   F    |  Asian   |   18-25   |      280      |
|  India  |   F    |  Asian   |   26-35   |      405      |
|  India  |   F    |  Asian   |   36-45   |      356      |
|  India  |   F    |  Asian   |   46-60   |      542      |
|  India  |   F    |  Asian   |    60+    |      699      |
|  India  |   F    |  Black   |   18-25   |      262      |
|  India  |   F    |  Black   |   26-35   |      360      |
|  India  |   F    |  Black   |   36-45   |      341      |
|  India  |   F    |  Black   |   46-60   |      569      |
|  India  |   F    |  Black   |    60+    |      681      |
|  India  |   F    | Hispanic |   18-25   |      259      |
|  India  |   F    | Hispanic |   26-35   |      343      |
|  India  |   F    | Hispanic |   36-45   |      352      |
|  India  |   F    | Hispanic |   46-60   |      539      |
|  India  |   F    | Hispanic |    60+    |      718      |
|  India  |   F    |  Other   |   18-25   |      258      |
|  India  |   F    |  Other   |   26-35   |      347      |
|  India  |   F    |  Other   |   36-45   |      337      |
|  India  |   F    |  Other   |   46-60   |      533      |
|  India  |   F    |  Other   |    60+    |      703      |
|  India  |   F    |  White   |   18-25   |      276      |
|  India  |   F    |  White   |   26-35   |      329      |
|  India  |   F    |  White   |   36-45   |      377      |
|  India  |   F    |  White   |   46-60   |      528      |
|  India  |   F    |  White   |    60+    |      649      |
|  India  |   M    |  Asian   |   18-25   |      237      |
|  India  |   M    |  Asian   |   26-35   |      355      |
|  India  |   M    |  Asian   |   36-45   |      380      |
|  India  |   M    |  Asian   |   46-60   |      507      |
|  India  |   M    |  Asian   |    60+    |      690      |
|  India  |   M    |  Black   |   18-25   |      273      |
|  India  |   M    |  Black   |   26-35   |      348      |
|  India  |   M    |  Black   |   36-45   |      321      |
|  India  |   M    |  Black   |   46-60   |      533      |
|  India  |   M    |  Black   |    60+    |      730      |
|  India  |   M    | Hispanic |   18-25   |      284      |
|  India  |   M    | Hispanic |   26-35   |      354      |
|  India  |   M    | Hispanic |   36-45   |      318      |
|  India  |   M    | Hispanic |   46-60   |      528      |
|  India  |   M    | Hispanic |    60+    |      711      |
|  India  |   M    |  Other   |   18-25   |      284      |
|  India  |   M    |  Other   |   26-35   |      342      |
|  India  |   M    |  Other   |   36-45   |      356      |
|  India  |   M    |  Other   |   46-60   |      538      |
|  India  |   M    |  Other   |    60+    |      679      |
|  India  |   M    |  White   |   18-25   |      268      |
|  India  |   M    |  White   |   26-35   |      347      |
|  India  |   M    |  White   |   36-45   |      369      |
|  India  |   M    |  White   |   46-60   |      501      |
|  India  |   M    |  White   |    60+    |      702      |
|   USA   |   F    |  Asian   |   18-25   |      260      |
|   USA   |   F    |  Asian   |   26-35   |      334      |
|   USA   |   F    |  Asian   |   36-45   |      366      |
|   USA   |   F    |  Asian   |   46-60   |      475      |
|   USA   |   F    |  Asian   |    60+    |      712      |
|   USA   |   F    |  Black   |   18-25   |      272      |
|   USA   |   F    |  Black   |   26-35   |      351      |
|   USA   |   F    |  Black   |   36-45   |      377      |
|   USA   |   F    |  Black   |   46-60   |      523      |
|   USA   |   F    |  Black   |    60+    |      664      |
|   USA   |   F    | Hispanic |   18-25   |      280      |
|   USA   |   F    | Hispanic |   26-35   |      333      |
|   USA   |   F    | Hispanic |   36-45   |      347      |
|   USA   |   F    | Hispanic |   46-60   |      535      |
|   USA   |   F    | Hispanic |    60+    |      670      |
|   USA   |   F    |  Other   |   18-25   |      275      |
|   USA   |   F    |  Other   |   26-35   |      325      |
|   USA   |   F    |  Other   |   36-45   |      368      |
|   USA   |   F    |  Other   |   46-60   |      487      |
|   USA   |   F    |  Other   |    60+    |      670      |
|   USA   |   F    |  White   |   18-25   |      290      |
|   USA   |   F    |  White   |   26-35   |      324      |
|   USA   |   F    |  White   |   36-45   |      333      |
|   USA   |   F    |  White   |   46-60   |      550      |
|   USA   |   F    |  White   |    60+    |      720      |
|   USA   |   M    |  Asian   |   18-25   |      270      |
|   USA   |   M    |  Asian   |   26-35   |      337      |
|   USA   |   M    |  Asian   |   36-45   |      334      |
|   USA   |   M    |  Asian   |   46-60   |      551      |
|   USA   |   M    |  Asian   |    60+    |      677      |
|   USA   |   M    |  Black   |   18-25   |      296      |
|   USA   |   M    |  Black   |   26-35   |      323      |
|   USA   |   M    |  Black   |   36-45   |      337      |
|   USA   |   M    |  Black   |   46-60   |      516      |
|   USA   |   M    |  Black   |    60+    |      712      |
|   USA   |   M    | Hispanic |   18-25   |      247      |
|   USA   |   M    | Hispanic |   26-35   |      336      |
|   USA   |   M    | Hispanic |   36-45   |      332      |
|   USA   |   M    | Hispanic |   46-60   |      505      |
|   USA   |   M    | Hispanic |    60+    |      620      |
|   USA   |   M    |  Other   |   18-25   |      262      |
|   USA   |   M    |  Other   |   26-35   |      372      |
|   USA   |   M    |  Other   |   36-45   |      334      |
|   USA   |   M    |  Other   |   46-60   |      524      |
|   USA   |   M    |  Other   |    60+    |      730      |
|   USA   |   M    |  White   |   18-25   |      255      |
|   USA   |   M    |  White   |   26-35   |      330      |
|   USA   |   M    |  White   |   36-45   |      354      |
|   USA   |   M    |  White   |   46-60   |      528      |
|   USA   |   M    |  White   |    60+    |      709      |
+---------+--------+----------+-----------+---------------+

In [339]:
# 7.Top 5 Violations with Highest Arrest Rates

query = """
SELECT 
    violation,
    COUNT(*) AS total_stops,
    SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) AS total_arrests,
    ROUND((SUM(CASE WHEN is_arrested = 1 THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS arrest_rate
FROM traffic_stops
GROUP BY violation
ORDER BY arrest_rate DESC
LIMIT 5;
"""

# Execute the query
mycursor.execute(query)

# Fetch the results
results = mycursor.fetchall()

# Create and display the table in a readable format using PrettyTable
table = PrettyTable()
table.field_names = ["Violation", "Total Stops", "Total Arrests", "Arrest Rate (%)"]

# Add each result row to the table
for row in results:
    table.add_row(row)

# Print the table
print(table)

+-----------+-------------+---------------+-----------------+
| Violation | Total Stops | Total Arrests | Arrest Rate (%) |
+-----------+-------------+---------------+-----------------+
|    DUI    |    13075    |      6610     |      50.55      |
|  Seatbelt |    13007    |      6573     |      50.53      |
|  Speeding |    13150    |      6598     |      50.17      |
|   Signal  |    13112    |      6549     |      49.95      |
|   Other   |    13194    |      6516     |      49.39      |
+-----------+-------------+---------------+-----------------+